version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/typescript"
    schedule:
      interval: "weekly"
    groups:
      typescript-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 1
